#ifndef BOARDS_H_INCLUDED
#define BOARDS_H_INCLUDED

char *boards[] = {
    "/a/ - Anime & Manga",
    "/b/ - Random",
    "/c/ - Anime/Cute",
    "/d/ - Hentai / Alternative",
    "/e/ - Ecchi",
    "/g/ - Technology",
    "/gif/ - Animated GIF",
    "/h/ - Hentai",
    "/hr/ - High Resolution",
    "/k/ - Weapons",
    "/m/ - Mecha",
    "/o/ - Auto",
    "/p/ - Photography",
    "/r/ - Request",
    "/s/ - Sexy Beautiful Women",
    "/t/ - Torrents",
    "/u/ - Yuri",
    "/v/ - The Vidya",
    "/w/ - Anime/Wallpapers",
    "/wg/ - Wallpapers/General",
    "/i/ - Oekaki",
    "/ic/ - Artwork/Critique",
    "/cm/ - Cute/Male",
    "/y/ - Yaoi",
    "/r9k/ - ROBOT9000",
    "/an/ - Animals & Nature",
    "/cgl/ - Cosplay & EGL",
    "/ck/ - Food & Cooking",
    "/co/ - Comics & Cartoons",
    "/fa/ - Fashion",
    "/fit/ - Health & Fitness",
    "/jp/ - Japan/General",
    "/mu/ - Music",
    "/n/ - Transportation",
    "/po/ - Papercraft & Origami",
    "/sp/ - Sports",
    "/tg/ - Traditional Games",
    "/toy/ - Toys",
    "/trv/ - Travel",
    "/tv/ - Television & Film",
    "/x/ - Paranormal" };
    
char *postlocations[] = {
    "http://sys.4chan.org/a/post",
    "http://sys.4chan.org/b/post",
    "http://sys.4chan.org/c/post",
    "http://sys.4chan.org/d/post",
    "http://sys.4chan.org/e/post",
    "http://sys.4chan.org/g/post",
    "http://sys.4chan.org/gif/post",
    "http://sys.4chan.org/h/post",
    "http://sys.4chan.org/hr/post",
    "http://sys.4chan.org/k/post",
    "http://sys.4chan.org/m/post",
    "http://sys.4chan.org/o/post",
    "http://sys.4chan.org/p/post",
    "http://sys.4chan.org/r/post",
    "http://sys.4chan.org/s/post",
    "http://sys.4chan.org/t/post",
    "http://sys.4chan.org/u/post",
    "http://sys.4chan.org/v/post",
    "http://sys.4chan.org/w/post",
    "http://sys.4chan.org/wg/post",
    "http://sys.4chan.org/i/post",
    "http://sys.4chan.org/ic/post",
    "http://sys.4chan.org/cm/post",
    "http://sys.4chan.org/y/post",
    "http://sys.4chan.org/r9k/post",
    "http://sys.4chan.org/an/post",
    "http://sys.4chan.org/cgl/post",
    "http://sys.4chan.org/ck/post",
    "http://sys.4chan.org/co/post",
    "http://sys.4chan.org/fa/post",
    "http://sys.4chan.org/fit/post",
    "http://sys.4chan.org/jp/post",
    "http://sys.4chan.org/mu/post",
    "http://sys.4chan.org/n/post",
    "http://sys.4chan.org/po/post",
    "http://sys.4chan.org/sp/post",
    "http://sys.4chan.org/tg/post",
    "http://sys.4chan.org/toy/post",
    "http://sys.4chan.org/trv/post",
    "http://sys.4chan.org/tv/post",
    "http://sys.4chan.org/x/post" };
    
#endif // BOARDS_H_INCLUDED
